// services/reminderService.js - Reminder management for birthdays and events

const { db, OBJECT_STORES } = require('./indexedDB.js');
const characterService = require('./characterService.js');

/**
 * Create a new reminder
 */
async function createReminder(reminderData) {
  const userId = reminderData.userId || 1;

  const newReminder = {
    userId,
    characterId: reminderData.characterId,
    guanxiId: reminderData.guanxiId || null,
    
    // Reminder details
    title: reminderData.title,
    description: reminderData.description || '',
    reminderType: reminderData.reminderType || 'custom', // birthday/anniversary/custom
    
    // Timing
    reminderDate: reminderData.reminderDate, // YYYY-MM-DD
    reminderTime: reminderData.reminderTime || '09:00', // HH:MM
    
    // Recurrence
    isRecurring: reminderData.isRecurring || false,
    recurrencePattern: reminderData.recurrencePattern || null, // yearly/monthly/weekly/daily
    
    // Advance notification
    advanceNotice: reminderData.advanceNotice || 0, // Days before to remind
    
    // Status
    status: 'pending', // pending/triggered/dismissed/snoozed
    lastTriggeredAt: null,
    snoozeUntil: null,
    
    // Metadata
    isAutoGenerated: reminderData.isAutoGenerated || false,
    metadata: reminderData.metadata || {}
  };

  return await db.add(OBJECT_STORES.REMINDERS, newReminder);
}

/**
 * Update reminder
 */
async function updateReminder(id, updates) {
  const existing = await db.getById(OBJECT_STORES.REMINDERS, id);
  
  if (!existing) {
    throw new Error(`Reminder with id ${id} not found`);
  }

  const updated = {
    ...existing,
    ...updates,
    updatedAt: Date.now()
  };

  await db.update(OBJECT_STORES.REMINDERS, id, updated);
  return updated;
}

/**
 * Delete reminder
 */
async function deleteReminder(id) {
  await db.delete(OBJECT_STORES.REMINDERS, id);
}

/**
 * Get pending reminders
 */
async function getPendingReminders(limit = 50) {
  const now = new Date();
  const today = now.toISOString().split('T')[0];
  const currentTime = `${now.getHours().toString().padStart(2, '0')}:${now.getMinutes().toString().padStart(2, '0')}`;

  const allReminders = await db.query(OBJECT_STORES.REMINDERS, { status: 'pending' });

  // Filter reminders that should trigger today
  const dueReminders = allReminders.filter(reminder => {
    // Skip if snoozed
    if (reminder.snoozeUntil && new Date(reminder.snoozeUntil) > now) {
      return false;
    }

    // Check date
    const reminderDate = new Date(reminder.reminderDate);
    const todayDate = new Date(today);

    // Apply advance notice
    const effectiveDate = new Date(reminderDate);
    effectiveDate.setDate(effectiveDate.getDate() - (reminder.advanceNotice || 0));

    if (effectiveDate.toISOString().split('T')[0] === today) {
      // Check if time has passed
      if (reminder.reminderTime <= currentTime) {
        return true;
      }
    }

    return false;
  });

  // Enrich with character info
  for (const reminder of dueReminders) {
    if (reminder.characterId) {
      reminder.character = await characterService.getCharacterById(reminder.characterId);
    }
  }

  return dueReminders.slice(0, limit);
}

/**
 * Trigger a reminder (mark as triggered)
 */
async function triggerReminder(id) {
  const reminder = await db.getById(OBJECT_STORES.REMINDERS, id);
  
  if (!reminder) {
    throw new Error(`Reminder with id ${id} not found`);
  }

  // Update status
  await db.update(OBJECT_STORES.REMINDERS, id, {
    ...reminder,
    status: 'triggered',
    lastTriggeredAt: Date.now()
  });

  // If recurring, create next instance
  if (reminder.isRecurring && reminder.recurrencePattern) {
    await createNextRecurrence(reminder);
  }
}

/**
 * Dismiss a reminder
 */
async function dismissReminder(id) {
  await updateReminder(id, { status: 'dismissed' });
}

/**
 * Snooze a reminder
 */
async function snoozeReminder(id, snoozeMinutes = 60) {
  const snoozeUntil = new Date(Date.now() + snoozeMinutes * 60000).toISOString();
  await updateReminder(id, { 
    status: 'snoozed',
    snoozeUntil 
  });
}

/**
 * Create next recurrence instance
 */
async function createNextRecurrence(reminder) {
  const currentDate = new Date(reminder.reminderDate);
  let nextDate;

  switch (reminder.recurrencePattern) {
    case 'daily':
      nextDate = new Date(currentDate);
      nextDate.setDate(nextDate.getDate() + 1);
      break;
    case 'weekly':
      nextDate = new Date(currentDate);
      nextDate.setDate(nextDate.getDate() + 7);
      break;
    case 'monthly':
      nextDate = new Date(currentDate);
      nextDate.setMonth(nextDate.getMonth() + 1);
      break;
    case 'yearly':
      nextDate = new Date(currentDate);
      nextDate.setFullYear(nextDate.getFullYear() + 1);
      break;
    default:
      return; // No recurrence
  }

  // Create new reminder instance
  await createReminder({
    ...reminder,
    id: undefined, // New ID will be generated
    reminderDate: nextDate.toISOString().split('T')[0],
    status: 'pending',
    lastTriggeredAt: null,
    snoozeUntil: null
  });
}

/**
 * Auto-generate birthday reminders for all characters
 */
async function generateBirthdayReminders(daysInAdvance = 3) {
  const characters = await characterService.getAllCharacters();
  const generated = [];

  for (const character of characters) {
    if (!character.birthday?.solar) continue;

    // Check if birthday reminder already exists
    const existing = await db.query(OBJECT_STORES.REMINDERS, {
      characterId: character.id,
      reminderType: 'birthday',
      isRecurring: true
    });

    if (existing.length === 0) {
      // Extract month and day
      const [year, month, day] = character.birthday.solar.split('-');
      const currentYear = new Date().getFullYear();
      const birthdayThisYear = `${currentYear}-${month}-${day}`;

      const reminder = await createReminder({
        characterId: character.id,
        title: `${character.displayName || character.name}的生日`,
        description: `提醒：${character.displayName || character.name}的生日即将到来`,
        reminderType: 'birthday',
        reminderDate: birthdayThisYear,
        reminderTime: '09:00',
        isRecurring: true,
        recurrencePattern: 'yearly',
        advanceNotice: daysInAdvance,
        isAutoGenerated: true
      });

      generated.push(reminder);
    }
  }

  return generated;
}

/**
 * Get all reminders for a character
 */
async function getRemindersForCharacter(characterId) {
  return await db.query(OBJECT_STORES.REMINDERS, { characterId });
}

/**
 * Get upcoming reminders (next N days)
 */
async function getUpcomingReminders(days = 7) {
  const now = new Date();
  const endDate = new Date(now);
  endDate.setDate(endDate.getDate() + days);

  const allReminders = await db.query(OBJECT_STORES.REMINDERS, { status: 'pending' });

  const upcoming = allReminders.filter(reminder => {
    const reminderDate = new Date(reminder.reminderDate);
    const effectiveDate = new Date(reminderDate);
    effectiveDate.setDate(effectiveDate.getDate() - (reminder.advanceNotice || 0));

    return effectiveDate >= now && effectiveDate <= endDate;
  });

  // Sort by date
  upcoming.sort((a, b) => {
    const dateA = new Date(a.reminderDate);
    const dateB = new Date(b.reminderDate);
    return dateA - dateB;
  });

  // Enrich with character info
  for (const reminder of upcoming) {
    if (reminder.characterId) {
      reminder.character = await characterService.getCharacterById(reminder.characterId);
    }
  }

  return upcoming;
}

module.exports = {
  createReminder,
  updateReminder,
  deleteReminder,
  getPendingReminders,
  triggerReminder,
  dismissReminder,
  snoozeReminder,
  generateBirthdayReminders,
  getRemindersForCharacter,
  getUpcomingReminders
};
